FROM registry.access.redhat.com/ubi8/ubi

RUN  curl -L https://golang.org/dl/go1.17.2.linux-amd64.tar.gz > golang.tar.gz \
  && rm -rf /usr/local/go && tar -C /usr/local -xzf golang.tar.gz \
  && rm golang.tar.gz \
  && echo "export PATH=$PATH:/usr/local/go/bin" > ~/.bashrc \
  && curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash \
  && source ~/.bashrc \
  && nvm install node
